version: "3.9"

x-syslog-driver: &syslog-driver
  logging:
    driver: syslog
    options:
      syslog-address: "udp://rsyslog:514"
      tag: "{{.Name}}/{{.ID}}"

x-jsonlog-driver: &jsonlog-driver
  logging:
    driver: "json-file"

x-common: &common
  restart: unless-stopped
  stdin_open: true
  tty: true

x-app-root: &app-root
  APP_ROOT: /app

x-args: &args
  args:
    <<: *app-root
    NODE_MAJOR: 16
    NEST_CLI_VERSION: 8.2.4
    NG_CLI_VERSION: 13.3.1
    ENVIRONMENT: development
    APP_HOSTNAME: localhost

x-envs: &envs
  environment:
    - TZ=Asia/Krasnoyarsk

x-app: &app
  <<: *common
  <<: *envs
  image:  rooms-js-app--development
  build:
    <<: *args
    context: .
    dockerfile: ./.docker/Dockerfiles/app.dev.Dockerfile
  volumes:
    - ./:/app
    - backend-node_modules:/app/backend/node_modules
    - frontend-node_modules:/app/frontend/node_modules
  networks:
    - rooms-js--development
  tmpfs:
    - /tmp

services:
  runner:
    <<: *app
    container_name: rooms-js-runner--development
    command: /bin/bash

  backend:
    <<: *app
    <<: *jsonlog-driver
#    <<: *syslog-driver
    container_name: rooms-js-backend--development
    working_dir: /app/backend
    ports:
      - "30044:3000"
    depends_on:
      - database
    command: yarn start:debug

  frontend:
    <<: *app
    <<: *jsonlog-driver
#    <<: *syslog-driver
    container_name: rooms-js-frontend--development
    working_dir: /app/frontend
    ports:
      - "42044:4200"
    depends_on:
      - backend
    command: yarn start

  webserver:
    <<: *jsonlog-driver
#    <<: *syslog-driver
    <<: *common
    build:
      context: .
      dockerfile: .docker/Dockerfiles/webserver.dev.Dockerfile
    container_name: rooms-js-webserver--development
    ports:
      - "28044:80"
      - "24044:443"
    volumes:
      - ./:/app
    networks:
      - rooms-js--development
    depends_on:
      - frontend

  database:
    <<: *jsonlog-driver
#    <<: *syslog-driver
    <<: *common
    image: mysql:5.7
    container_name: rooms-js-database--development
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "44039:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rooms-js--development
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci


volumes:
  backend-node_modules:
  frontend-node_modules:
  mysql-data:

networks:
  rooms-js--development:
